/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Todoapp;

import Controller.ProjectController;
import java.util.Date;
import model.Project;

public class App {
   
    public static void main(String[] args) throws ClassNotFoundException {
        
        ProjectController projectController = new ProjectController ();
        
        Project project = new  Project();
        project.setName ("Projeto teste");
        project.setDescription ("Descrição teste");
        projectController.save(project);

//        project.setName ( "Novo nome de projeto");
//        projectController.update(project);

//        List<project> projects = projectController.getAll();
//        System.out.println ("Total de projetos: " + projects.size());
    }

    Object getGreeting () {
        throw new UnsupportedOperationException ( "Not supported yet." ); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
