/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Todoapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       var classUnderTest = newApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private App newApp() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

